apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-170246418
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-170246418
    app.kubernetes.io/part-of: test-app-170246418
  name: python-basic-170246418
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: python-basic-170246418
status:
  loadBalancer: {}
